# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(0A0503)
$foreground = rgb(B2ACA9)
$color0 = rgb(494237)
$color1 = rgb(554841)
$color2 = rgb(97745D)
$color3 = rgb(6C836B)
$color4 = rgb(C28257)
$color5 = rgb(B5ACB1)
$color6 = rgb(FED995)
$color7 = rgb(88807C)
$color8 = rgb(605A57)
$color9 = rgb(554841)
$color10 = rgb(97745D)
$color11 = rgb(6C836B)
$color12 = rgb(C28257)
$color13 = rgb(B5ACB1)
$color14 = rgb(FED995)
$color15 = rgb(88807C)
