general {
    lock_cmd = hyprlock     
}

listener {
    timeout = 520                                
    on-timeout = loginctl lock-session           
}

listener {
    timeout = 600                                
    on-timeout = niri msg action power-off-monitors
}

