general {
    lock_cmd = pidof hyprlock || hyprlock       
}

listener {
    timeout = 520                                
    on-timeout = hyprlock           
}

listener {
    timeout = 600                                
    on-timeout = niri msg action power-off-monitors
}

