vo=gpu-next
gpu-api=vulkan
gpu-context=waylandvk
hwdec=nvdec-copy,vaapi-copy,auto-copy
profile=high-quality
dither-depth=auto
dither=error-diffusion
error-diffusion=sierra-lite

scale=ewa_lanczossharp
cscale=ewa_lanczossharp
dscale=mitchell
scale-antiring=0.6
cscale-antiring=0.6

deband=yes
deband-iterations=4
deband-threshold=48
deband-range=16
deband-grain=24
